dasist/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.contrib.auth.views import login, logout

import pprint

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',		'views.index'),
	url(r'^admin/',		include(admin.site.urls)),
	url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		login),
	url(r'^logout$',	logout),
	url(r'^core/',		include('core.urls')),
	url(r'^bills/',		include('bills.urls')),
	url(r'^scan/',		include('scan.urls')),
	url(r'^about$',		'views.about'),
)

kupa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/',		include(admin.site.urls)),
    url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
    url(r'^accounts/login/$',	login),
    url(r'^logout$',		logout),
    url(r'^about$',		TemplateView.as_view(template_name='about.html'), name='about'),
    #url(r'^$',			include('medrec.urls')),
    #url(r'^$',			TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$',			'medrec.views.index'),
    url(r'^c/a/$',		'medrec.views.client_add'),
    url(r'^c/(?P<pk>\d+)/$',	'medrec.views.client_view'),
    url(r'^c/(?P<pk>\d+)/u/$',	'medrec.views.client_edit'),
    url(r'^c/(?P<pk>\d+)/d/$',	'medrec.views.client_del'),
    url(r'^c/f/(?P<abc>\d+)/$',	'medrec.views.client_set_filter_abc'),
    url(r'^c/s/(?P<sort>\d+)/$','medrec.views.client_set_sort'),
    url(r'^r/(?P<pk>\d+)/$',	'medrec.views.record_view'),
    url(r'^r/(?P<pk>\d+)/u/$',	'medrec.views.record_edit'),
    url(r'^r/(?P<pk>\d+)/d/$',	'medrec.views.record_del'),
    url(r'^r/d/$',		'medrec.views.record_set_date'),
    url(r'^r/d/(?P<date>\d+)/$','medrec.views.record_get_date'),
    url(r'^i/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_view'),
    url(r'^i/d/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_del'),
]
#urlpatterns += staticfiles_urlpatterns()

sandbox/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',				'views.index'),
	url(r'^admin/',				include(admin.site.urls)),
	url(r'^admin/jsi18n',			'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$',	'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		'django.contrib.auth.views.login'),
	url(r'^logout$',			'django.contrib.auth.views.logout'),
	url(r'^filer/',				include('filer.urls')),
	url(r'^about$',				'views.about'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reception/', include('reception.urls')),
    url(r'^clients/', include('clients.urls')),


)

dasist-0.2.0/dasist/contract/models.py
"""
contract.models
"""

# 2. django
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver
# 3. local
from core.models import FileSeq
from contrib.models import Org, State, Role, Approver, Place, Subject, Department, Payer, Customer
from invoice.views_extras import ROLE_ACCOUNTER, ROLE_CHIEF


class Contract(models.Model):
    fileseq = models.OneToOneField(FileSeq, on_delete=models.CASCADE, primary_key=True, verbose_name='Файлы')
    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name='place_contracts', db_index=True, verbose_name='Объект')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='subject_contracts', null=True, blank=True, db_index=True, verbose_name='ПодОбъект')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='customer_contracts', null=True, blank=True, db_index=True, verbose_name='Заказчик')
    depart = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='department_contracts', null=True, blank=True, db_index=True, verbose_name='Направление')
    payer = models.ForeignKey(Payer, on_delete=models.CASCADE, related_name='payer_contracts', db_index=True, verbose_name='Наша фирма')
    shipper = models.ForeignKey(Org, on_delete=models.CASCADE, related_name='shipper_contracts', db_index=True, verbose_name='Контрагент')
    assign = models.ForeignKey(Approver, on_delete=models.CASCADE, related_name='assigned_contracts', db_index=True, verbose_name='Исполнитель')
    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='state_contracts', db_index=True, verbose_name='Состояние')
    doc_no = models.CharField(max_length=32, db_index=True, verbose_name='Номер договора')    # max=11
    doc_date = models.DateField(db_index=True, verbose_name='Дата договора')
    doc_sum = models.DecimalField(max_digits=11, decimal_places=2, null=True, db_index=True, verbose_name='Сумма договора')

    def __str__(self):
        return str(self.pk)

    def set_state_id(self, pk):
        self.state = State.objects.get(pk=pk)

    def get_state_id(self):
        return self.state.pk

    def get_state_name(self):
        return self.state.name

    def get_state_color(self):
        return self.state.color

    def get_mgr(self):
        return self.route_set.get(role=ROLE_CHIEF)

    def get_booker(self):
        return self.route_set.get(role=ROLE_ACCOUNTER)

    def get_is_signatory(self, approver):
        return self.route_set.get(approve=approver)

    class Meta:
        db_table = 'contract'
        verbose_name = 'Договор'
        verbose_name_plural = 'Договора'


@receiver(post_delete, sender=Contract)
def _contract_delete(sender, instance, **kwargs):
    instance.fileseq.delete()


class Route(models.Model):
    doc = models.ForeignKey(Contract, on_delete=models.CASCADE, db_index=True, verbose_name='Договор')
    role = models.ForeignKey(Role, on_delete=models.CASCADE, related_name='+', db_index=True, verbose_name='Роль')
    approve = models.ForeignKey(Approver, on_delete=models.CASCADE, related_name='+', db_index=True, verbose_name='Подписант')
    done = models.BooleanField(db_index=True, default=False, verbose_name='Согласовано')

    def __str__(self):
        return '%d: %s: %d' % (self.contract.pk, self.approve.get_fio() if self.approve else self.role.name, int(self.done))

    def get_str(self):
        return self.approve.get_fio() if self.approve else self.role.name

    class Meta:
        unique_together = ('contract', 'role')
        ordering = ('contract',)
        verbose_name = 'Подписант'
        verbose_name_plural = 'Подписанты'


class Event(models.Model):
    doc = models.ForeignKey(Contract, on_delete=models.CASCADE, db_index=True, verbose_name='Договор')
    ctime = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ДатаВремя')
    approve = models.ForeignKey(Approver, on_delete=models.CASCADE, related_name='+', db_index=True, verbose_name='Подписант')
    comment = models.TextField(null=True, blank=True, verbose_name='Камменты')

    def __str__(self):
        return '%s: %s' % (self.approve, self.comment)

    class Meta:
        ordering = ('ctime',)
        verbose_name = 'Резолюция'
        verbose_name_plural = 'Резолюции'

dasist/core/models.py
# -*- coding: utf-8 -*-

# 1. django
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.core.files.base import ContentFile

# 2. 3rd parties
#from sortedm2m.fields import SortedManyToManyField

# 3. system
import os, datetime, hashlib, uuid
from StringIO import StringIO

# 4. local
from rfm import RenameFilesModel

def    my_upload_to(instance, filename):
	'''
	Generates upload path for FileField
	'''
	instance.name = filename
	#return u'temp/%s' % filename
	return u'temp/%s' % uuid.uuid4().hex.upper()

def file_md5(file, block_size=1024*14):
	'''
	file_md5(file, use_system = False) -> md5sum of "file" as hexdigest string.
	"file" may be a file name or file object, opened for read.
	If "use_system" is True, if possible use system specific program. This ignore, if file object given.
	"block_size" -- size in bytes buffer for calc md5. Used with "use_system=False".
	'''
	if isinstance(file, basestring):
		file = open(file, 'rb')
	h = hashlib.md5()
	block = file.read(block_size)
	while block:
		h.update(block)
		block = file.read(block_size)
	return h.hexdigest()

class	File(RenameFilesModel):
	'''
	TODO:
	* delete
	'''
	#filename	= models.CharField(max_length=255, db_index=True, blank=False, verbose_name=u'Filename')
	#mimetype	= models.CharField(max_length=64, verbose_name=u'MIME')
	#size

	#file	= models.FileField(null=False, upload_to=my_upload_to, verbose_name=u'Файл')    # attrs: name, path, url, size
	file	= models.FileField(null=False, upload_to=my_upload_to, verbose_name=u'Файл')    # attrs: name, path, url, size
	name	= models.CharField(null=False, db_index=True, blank=False, max_length=255, verbose_name=u'Имя файла')
	mime	= models.CharField(null=False, blank=False, max_length=255, verbose_name=u'Тип Mime')
	ctime	= models.DateTimeField(null=False, blank=False, auto_now_add=True, verbose_name=u'Записано')
	size	= models.PositiveIntegerField(null=False, blank=False, verbose_name=u'Размер')
	md5	= models.CharField(null=False, blank=False, max_length=32, verbose_name=u'MD5')
	#RENAME_FILES    = {'file': {'dest': settings.BILLS_ROOT, 'keep_ext': False}}
	RENAME_FILES    = {'file': {'dest': '', 'keep_ext': False}}

	def	save(self):
		'''
		New: file = <InMemoryUploadedFile: 2.html (text/html)>
		django...file: _get_size
		'''
		#if (self.file._file):	# FIXME: костыль, надо not isinstance(FieldFile)
		self.mime = self.file._file.content_type
		self.size = self.file._file._size
		self.md5 = file_md5(self.file._file.file)
		super(File, self).save()	# unicode error
		#else:
		#	super(File, self).save()

	#def	delete(self):
	#	os.unlink(self.get_path())
	#	super(File, self).delete()

	def	raw_save(self):
		'''
		For import only
		'''
		super(File, self).save()

	#def     __unicode__(self):
	#	return self.name

	def	get_filename(self):
		return '%08d' % self.pk

	def	get_path(self):
		return os.path.join(settings.MEDIA_ROOT, '%08d' % self.pk)

	class   Meta:
		verbose_name            = u'Файл'
		verbose_name_plural     = u'Файлы'

class	FileSeq(models.Model):
	'''
	File sequence
	TODO:
	- del file
	'''
	files	= models.ManyToManyField(File, null=True, blank=True, through='FileSeqItem', verbose_name=u'Файлы')

	def     __unicode__(self):
		return str(self.pk)

	def	clean_children(self):
		'''
		'''
		self.files.all().delete()

	def	purge(self):
		'''
		Delete self and all files in
		'''
		self.clean_children()
		super(FileSeq, self).delete()

	def	add_file(self, f):
		'''
		'''
		FileSeqItem(file=f, fileseq=self, order=self.files.count()+1).save()

	class   Meta:
		#unique_together		= (('scan', 'type', 'name'),)
		ordering                = ('id',)
		verbose_name            = u'Последовательность файлов'
		verbose_name_plural     = u'Последовательности файлов'

class	FileSeqItem(models.Model):
	file	= models.OneToOneField(File, primary_key=True, verbose_name=u'Файл')
	fileseq	= models.ForeignKey(FileSeq, null=False, blank=False, verbose_name=u'Последовательность файлов')
	order	= models.PositiveSmallIntegerField(null=False, blank=False, verbose_name=u'#')

	#def	__unicode__(self):
	#	return '%s: %s' % (self.user, self.comment)

	#def	delete(self):
	#	pass

	#def	swap(self, sibling):
	#	pass

	class   Meta:
		ordering                = ('file', 'order',)
		verbose_name            = u'Файл последовательности'
		verbose_name_plural     = u'Файлы последовательности'

dasist-0.2.0/dasist/contrarch/forms.py
"""
contrarch.forms
"""

# 1. system
import datetime
# 2. django
from django import forms
# 3. 3rd
from dal import autocomplete
# 4. my
from core.models import Org
from .models import Contrarch


EMPTY_VALUE = [('', '---'), ]


class FilterContrarchListForm(forms.Form):
    place = forms.ChoiceField(choices=EMPTY_VALUE + list(Contrarch.objects.order_by('place').distinct().values_list('place', 'place')), label=u'Объект', required=False)
    subject = forms.ChoiceField(choices=EMPTY_VALUE + list(Contrarch.objects.order_by('subject').distinct().values_list('subject', 'subject')), label=u'Подобъект', required=False)
    customer = forms.ChoiceField(choices=EMPTY_VALUE + list(Contrarch.objects.order_by('customer').distinct().exclude(customer=None).values_list('customer', 'customer')), label=u'Заказчик', required=False)
    depart = forms.ChoiceField(choices=EMPTY_VALUE + list(Contrarch.objects.order_by('depart').distinct().exclude(depart=None).values_list('depart', 'depart')), label=u'Направление', required=False)
    payer = forms.ChoiceField(choices=EMPTY_VALUE + list(Contrarch.objects.order_by('payer').distinct().exclude(payer=None).values_list('payer', 'payer')), label=u'Плательщик', required=False)
    shipper = forms.ModelChoiceField(queryset=Org.objects.all(), required=False, widget=autocomplete.ModelSelect2(url='org-autocomplete'))
    docno = forms.CharField(max_length=64, label=u'Номер договора', required=False)
    docdate = forms.CharField(label=u'Дата договора', required=False, widget=forms.TextInput(attrs={'size': 8}))

    def clean_docdate(self):
        data = self.cleaned_data['docdate']
        if data:
            try:
                datetime.datetime.strptime(data, '%d.%m.%y')
                return data
            except ValueError:
                self.cleaned_data['docdate'] = ''
                raise forms.ValidationError('Must be "DD.MM.YY"')

    def __init__(self, *args, **kwargs):
        forms.Form.__init__(self, *args, **kwargs)
        places = EMPTY_VALUE + list(Contrarch.objects.order_by('place').distinct().values_list('place', 'place'))
        if len(places) == 1:
            self.fields['place'].initial = places[0][0]
        place = self.fields['place'].initial or self.initial.get('place')
        if place:
            # parent is known. Now I can display the matching children.
            subjects = EMPTY_VALUE + list(Contrarch.objects.filter(place=place).order_by('subject').distinct().exclude(subject=None).values_list('subject', 'subject'))
            self.fields['subject'].choices = subjects
            if len(subjects) == 1:
                self.fields['subject'].initial = subjects[0][0]

dasist-0.2.0/dasist/contrib/forms.py
from django import forms

from . import models


class InnField(forms.CharField):
    @staticmethod
    def __chk_cs(s, k):
        """
        Calculates control summ
        @s:string - inn
        @k:tupple - digits positions to calculate
        """
        vap_sum = 0
        vap_len = len(k)
        for i in range(vap_len):
            vap_sum += int(s[i]) * k[i]
        return ((vap_sum % 11) % 10) % 11 == int(s[vap_len])    # ?..

    def validate(self, value):
        super(InnField, self).validate(value)
        if not value.isdigit():
            raise forms.ValidationError('Должны быть только цифры')
        if len(value) not in {10, 12}:
            raise forms.ValidationError('Должно быть 10 или 12 цифр')
        if len(value) == 10:
            if not self.__chk_cs(value, (2, 4, 10, 3, 5, 9, 4, 6, 8)):
                raise forms.ValidationError('Контрольная сумма цифр неверна')
        else:
            if not (self.__chk_cs(value, (3, 7, 2, 4, 10, 3, 5, 9, 4, 6, 8)) and
                    self.__chk_cs(value, (7, 2, 4, 10, 3, 5, 9, 4, 6, 8))):
                raise forms.ValidationError('Контрольные суммы цифр неверны')


def chk_new_org(inn, name):
    """
    Check new shipper on uniqueness
    @f:form object
    @flds:tupple - field to check (inn, shorname)
    """
    orgs = models.Org.objects.filter(name=name.strip())
    if (orgs.count()) and (orgs[0].inn != inn.strip()):
        raise forms.ValidationError('Поставщик с таким кратким наименованием и другим ИНН уже есть')


def chk_org_names(shortname, fullname):
    if shortname.strip() == fullname.strip():
        raise forms.ValidationError('Краткое и Полное наименования Поставщика совпадают. Не надо так делать.')


class OrgEditForm(forms.ModelForm):
    class Meta:
        model = models.Org
        exclude = []

dasist-0.2.0/dasist/core/forms.py
"""
core.forms
"""

from django import forms


class FileSeqItemAddForm(forms.Form):
    file = forms.FileField(label='File', required=False)

dasist/core/forms.py
# -*- coding: utf-8 -*-
'''
'''

from django import forms

import models

dasist-0.2.0/dasist/templates/invarch/base.html
{% extends "base.html" %}
{% block title %} Счета. Архив {% endblock %}
{% block menu_title %} <a href="{% url 'scan_list' %}"> Счета. Архив </a> {% endblock %}

dasist-0.2.0/dasist/templates/invarch/detail.html
{% extends "invarch/base.html" %}
{% block js %}
<script type="text/javascript">
	$(document).ready(function() {
		$('.image-pack').magnificPopup({
			delegate: 'a.image-link',
			type:'image',
			gallery: { enabled: true },
			image: { verticalFit: false }
		});
	});
</script>
{% endblock %}
{% block body_main %}

{% if user.is_staff %}
<a href="{% url 'scan_edit' object.pk %}" style="text-decoration: none;"> {% include "svgbutton/edit.html" %} </a>
{% endif %}
{% if next %}
 <a href="{% url 'scan_view' next.pk %}" style="text-decoration: none;"> {% include "svgbutton/page-prev.html" %} </a>
{% endif %}
{% if prev %}
 <a href="{% url 'scan_view' prev.pk %}" style="text-decoration: none;"> {% include "svgbutton/page-next.html" %} </a>
{% endif %}

<table border="0">
<tr>
<td valign="top">
<table border="1">
<caption>  Скан: </caption>
<tbody>
 <tr> <th> # </th> <td> {{ object.fileseq.pk }} </td> </tr>
 <tr> <th> Объект </th> <td> {{ object.place }} </td> </tr>
 <tr> <th> Подобъект </th> <td> {{ object.subject|default:"---" }} </td> </tr>
 <tr> <th> Направление </th> <td> {{ object.depart|default:"---" }} </td> </tr>
 <tr> <th> Плательщик </th> <td> {{ object.payer|default:"---" }} </td> </tr>
 <tr> <th> Поставщик </th> <td nowrap>
  {% if object.shipper %}
    {{ object.shipper.name }} <br/>
    ({{ object.shipper.fullname }}) <br/>
    ИНН: {{ object.shipper.inn }}
  {% else %}
   ---
  {% endif %}
  </td> </tr>
 <tr> <th> Продавец </th> <td> {{ object.supplier|default:"---" }} </td> </tr>
 <tr> <th> Счет </th> <td> № {{ object.no }} от {{ object.date|date:"d.m.y" }} на {{ object.sum|default:"---" }} руб. </td> </tr>
 <tr>
  <td> Оригинал: </td>
  <td margin="0" padding="0" class="image-pack">
   {% for img in object.fileseq.fileseqitem_set.all %}
     <a href="{% url 'file_get' img.pk %}" class="image-link" style="text-decoration: none;"> {% include "svgbutton/preview.html" %} </a>
     <a href="{% url 'file_get' img.pk %}" style="text-decoration: none;"> {% include "svgbutton/download.html" %} </a>
    <br/>
   {% endfor %}
  </td>
 </tr>
 </tbody>
</table>
</td>
<td valign="top">
<table border="1">
<caption> История: </caption>
<thead>
 <th> Ok </th>
 <th> Когда </th>
 <th> Кто </th>
 <th> Камменты </th>
</thead>
<tbody>
  {# for i in object.decode_events #}
  {% for i in object.event_set.all %}
  <tr>
   <td valign="top"> {% if i.resume %} {% include "svgbutton/agreed.html" %} {% else %} {% include "svgbutton/canceled.html" %} {% endif %} </td>
   <td valign="top" nowrap> {{ i.ctime|date:"d.m.y H:i" }} </td>
   <td valign="top"> {{ i.approve }} </td>
   <td valign="top"> {{ i.comment }} </td>
  </tr>
  {% endfor %}
</tbody>
</table>
</td>
</tr>
</table>

{% endblock %}

dasist-0.2.0/dasist/templates/invarch/form.html
{% extends "invarch/base.html" %}
{% block js %}
{{ form.media }}
{% include "handle_inn.html" %}
<script type="text/javascript">
        $(document).ready(function() {
                $('.image-pack').magnificPopup({
                        delegate: 'a.image-link',
                        type:'image',
                        gallery: { enabled: true },
                        image: { verticalFit: false }
                });
        });
</script>
{% endblock %}
{% block body_main %}
   <form enctype="multipart/form-data" action="" method="POST">
	{% csrf_token %}
	<table border="1">
		{{ form.as_table }}
 <tr>
  <td> Оригинал: </td>
  <td> <ol style="margin: 0" class="image-pack">
   {% for img in object.fileseq.fileseqitem_set.all %}
    <li>
     <a href="{% url 'file_get' img.pk %}" class="image-link" style="text-decoration: none"> {% include "svgbutton/preview.html" %} </a>
     <a href="{% url 'file_get' img.pk %}" style="text-decoration: none"> {% include "svgbutton/download.html" %} </a>
    </li>
   {% endfor %}
  </ol> </td>
 </tr>
	</table>
	<button type="submit" title="Записать" class="plain"> {% include "svgbutton/save.html" %} </button>
	<a href="{% url 'scan_view' object.pk %}"> <button type="button" title="Отказаться" class="plain"> {% include "svgbutton/cancel.html" %} </button> </a>
   </form>
{% endblock %}

dasist-0.2.0/dasist/templates/invarch/form_replace_depart.html
{% extends "invarch/base.html" %}
{% block js %}
{{ form.media }}
{% endblock %}
{% block body_main %}
   <form action="" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Ok </button>
   </form>
   {% if msg %}
   <p> {{ msg }} </p>
   {% endif %}
{% endblock %}

dasist-0.2.0/dasist/templates/invarch/form_replace_place.html
{% extends "invarch/base.html" %}
{% block js %}
{{ form.media }}
{% endblock %}
{% block body_main %}
   <form action="" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> Ok </button>
   </form>
   {% if msg %}
   <p> {{ msg }} </p>
   {% endif %}
{% endblock %}

dasist-0.2.0/dasist/templates/invarch/list.html
{% extends "invarch/base.html" %}
{% block js %}
<script type="text/javascript">
$(document).ready(function() {
	$('#id_place').change(function(){
		json_to_select('{% url "scan_get_subjects" %}?place=' + $(this).val(), '#id_subject');
	});
});
</script>
<script type="text/javascript" src="{{ STATIC_URL }}js/get_subjects.js"></script>
{% endblock %}
{% block body_main %}
{{ form.media }}
<table border="0">
<tr>
<td>
{% include "paginator.html" %}
</td>
<td>
 <label for="lpp">Строк:</label>
 <!--select onchange="document.location=this.options[this.selectedIndex].value"-->
 <select onchange="document.location=this.options[this.selectedIndex].value">
  <option value="{% url 'scan_set_lpp' 10 %}" {% ifequal lpp 10 %}selected{% endifequal %}>10</option>
  <option value="{% url 'scan_set_lpp' 15 %}" {% ifequal lpp 15 %}selected{% endifequal %}>15</option>
  <option value="{% url 'scan_set_lpp' 20 %}" {% ifequal lpp 20 %}selected{% endifequal %}>20</option>
  <option value="{% url 'scan_set_lpp' 25 %}" {% ifequal lpp 25 %}selected{% endifequal %}>25</option>
  <option value="{% url 'scan_set_lpp' 50 %}" {% ifequal lpp 50 %}selected{% endifequal %}>50</option>
 </select>
</td>
</tr>
</table>
<table>
 <thead>
 <tr>
  <th> # </th>
  <th> Объект </th>
  <th> Подобъект </th>
  <th> Направление </th>
  <th> Плательщик </th>
  <th> Поставщик </th>
  <th> Номер </th>
  <th> Дата </th>
  <th> Сумма </th>
 </tr>
<form action="{% url 'scan_set_filter' %}" method="POST">
 {% csrf_token %}
 <tr>
  <th/>
  <th> {{ form.place }} <br/> {{ form.place.errors }} </th>
  <th> {{ form.subject }} <br/> {{ form.subject.errors }} </th>
  <th> {{ form.depart }} <br/> {{ form.depart.errors }} </th>
  <th> {{ form.payer }} <br/> {{ form.payer.errors }} </th>
  <th> {{ form.shipper }} <br/> {{ form.shipper.errors }} </th>
  <th> {{ form.billno }} <br/> {{ form.billno.errors }} </th>
  <th> {{ form.billdate }} <br/> {{ form.billdate.errors }} </th>
  <th> <button type="submit" title="Фильтровать" class="plain"> {% include "svgbutton/filter.html" %} </button> </th>
 </tr>
</form>
 </thead>
 <tbody>
{% for object in object_list %}
 <tr>
  <td> <a href="{% url 'scan_view' object.pk %}"> {{ object.pk }} </a> </td>
  <td nowrap> {{ object.place }} </td>
  <td nowrap> {{ object.subject|default:"---" }} </td>
  <td nowrap> {% if object.depart %} {{ object.depart }} {% else %} --- {% endif %} </td>
  <td nowrap> {{ object.payer|default:"---" }} </td>
  <td nowrap> {{ object.shipper|default:"---" }} </td>
  <td nowrap> {{ object.no }} </td>
  <td nowrap> {{ object.date|date:"d.m.y" }} </td>
  <td nowrap align="right"> {{ object.sum|default:"---" }} </td>
 </tr>
{% endfor %}
</table>
{% endblock %}