dasist/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.contrib.auth.views import login, logout

import pprint

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',		'views.index'),
	url(r'^admin/',		include(admin.site.urls)),
	url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		login),
	url(r'^logout$',	logout),
	url(r'^core/',		include('core.urls')),
	url(r'^bills/',		include('bills.urls')),
	url(r'^scan/',		include('scan.urls')),
	url(r'^about$',		'views.about'),
)

kupa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/',		include(admin.site.urls)),
    url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
    url(r'^accounts/login/$',	login),
    url(r'^logout$',		logout),
    url(r'^about$',		TemplateView.as_view(template_name='about.html'), name='about'),
    #url(r'^$',			include('medrec.urls')),
    #url(r'^$',			TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$',			'medrec.views.index'),
    url(r'^c/a/$',		'medrec.views.client_add'),
    url(r'^c/(?P<pk>\d+)/$',	'medrec.views.client_view'),
    url(r'^c/(?P<pk>\d+)/u/$',	'medrec.views.client_edit'),
    url(r'^c/(?P<pk>\d+)/d/$',	'medrec.views.client_del'),
    url(r'^c/f/(?P<abc>\d+)/$',	'medrec.views.client_set_filter_abc'),
    url(r'^c/s/(?P<sort>\d+)/$','medrec.views.client_set_sort'),
    url(r'^r/(?P<pk>\d+)/$',	'medrec.views.record_view'),
    url(r'^r/(?P<pk>\d+)/u/$',	'medrec.views.record_edit'),
    url(r'^r/(?P<pk>\d+)/d/$',	'medrec.views.record_del'),
    url(r'^r/d/$',		'medrec.views.record_set_date'),
    url(r'^r/d/(?P<date>\d+)/$','medrec.views.record_get_date'),
    url(r'^i/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_view'),
    url(r'^i/d/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_del'),
]
#urlpatterns += staticfiles_urlpatterns()

sandbox/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',				'views.index'),
	url(r'^admin/',				include(admin.site.urls)),
	url(r'^admin/jsi18n',			'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$',	'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		'django.contrib.auth.views.login'),
	url(r'^logout$',			'django.contrib.auth.views.logout'),
	url(r'^filer/',				include('filer.urls')),
	url(r'^about$',				'views.about'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reception/', include('reception.urls')),
    url(r'^clients/', include('clients.urls')),


)

apps/gw/address/models.py
# -*- coding: utf-8 -*-

'''
lansite.gw.address.models.py
'''

from django.db import models
from django.contrib.auth.models import User

apps/gw/bits/models.py
# -*- coding: utf-8 -*-

'''
lansite.gw.bits.models.py
'''

from django.db import models
from django.contrib.auth.models import User
from polymorphic import PolymorphicModel
from treebeard.al_tree import AL_Node

import bigint

from ref.models import Kladr

class	GwUser(models.Model):
	user		= models.OneToOneField(User, primary_key=True, verbose_name=u'Пользователь')

	def	__unicode__(self):
		return self.user.username

	class	Meta:
		app_label = 'gw'
		ordering = ('user',)
		verbose_name = u'Пользователь GW'
		verbose_name_plural = u'Пользователи GW'

class	USManager(models.Manager):
	'''
	UserSetting manager
	'''
	def	cu_ufa(self, user, form, action, object, value):
		'''
		Create or update object/value/ for given user/form/action
		Used for sort set
		@param self:UserSetting object
		@param u:str - string
		@param f:str - string
		@param a:str - string
		@param o:str - string
		@param v:str - string
		'''
		q = self.filter(user=user, form=form, action=action)
		if (q):
			r = q[0]
			if ((r.object != object) or (r.value != value)):
				r.object = object
				r.value = value
				r.save()
		else:
			UserSetting(user=user, form=form, action=action, object=object, value=value).save()

	def	cu_ufao(self, user, form, action, object, value):
		'''
		Create or update object/value/ for given user/form/action
		Used for filter set
		@param self:UserSetting object
		@param u:str - string
		@param f:str - string
		@param a:str - string
		@param o:str - string
		@param v:str - string
		'''
		q = self.filter(user=user, form=form, action=action, object=object)
		if (q):
			r = q[0]
			if (r.value != value):
				r.value = value
				r.save()
		else:
			UserSetting(user=user, form=form, action=action, object=object, value=value).save()

	def	del_ufao(self, user, form, action, object = None):
		'''
		Delete all of given user/form/actions
		Used for delete sort|filters
		@param self:UserSetting object
		@param u:str - string
		@param f:str - string
		@param a:str - string
		'''
		if (o == None):
			self.filter(user=user, form=form, action=action).delete()
		else:
			self.filter(user=user, form=form, action=action, object=object).delete()

	def	get_sort(self, user, form):
		'''
		@return (order:str, name:str, value:int)
		'''
		retvalue = (None, None, None)
		sort = self.filter(user=user, form=form, action='sort')
		if sort:
			o = sort[0].object
			v = int(sort[0].value)	# 1/-1
			print sort[0].value
			if (v == 1):
				retvalue = (o, v, '-' + o)
			else:
				retvalue = (o, v, o)
		return retvalue

class	UserSetting(models.Model):
	user		= models.ForeignKey(User, blank=False, null=False, verbose_name=u'Пользователь')
	form		= models.CharField(max_length=16, blank=False, null=False, verbose_name=u'Форма')
	action		= models.CharField(max_length=16, blank=False, null=False, verbose_name=u'Действие')
	object		= models.CharField(max_length=16, blank=False, null=False, verbose_name=u'Объект')
	value		= models.CharField(max_length=16, blank=False, null=False, verbose_name=u'Значение')
	objects		= USManager()

	def	__unicode__(self):
		return u'%s.%s.%s.%s.%s' % (self.user.username, self.form, self.object, self.action, self.value )

	class	Meta:
		app_label = 'gw'
		ordering = ('user', 'form', 'object', 'action')
		verbose_name = u'Настройки пользователя'
		verbose_name_plural = u'Настройки пользователей'

class	Object(PolymorphicModel):
	'''
	Объект - прародитель всех остальных.
	'''
	'''
	child	= models.ManyToManyField('self', symmetrical=False, through='SubObject', verbose_name=u'Объекты')
	'''

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Объект'
		verbose_name_plural	= u'Объекты'

'''
class	SubObject(models.Model):
	master		= models.ForeignKey(Object, related_name='slave', verbose_name=u'Хозяин')
	slave		= models.OneToOneField(Object, related_name='master', primary_key=True, verbose_name=u'Объект')

	class	Meta:
		verbose_name		= u'Подобъект'
		verbose_name_plural	= u'Подобъекты'
'''

class	AddrShort(models.Model):
	'''
	Сокращение для адреса: ул.=улица etc
	'''
	name		= models.CharField(max_length=10, blank=False, unique=True, verbose_name=u'Краткое наименование')
	fullname	= models.CharField(max_length=64, blank=False, unique=True, verbose_name=u'Полное наименование')

	def	__unicode__(self):
		return u'%s (%s)' % (self.name, self.fullname)

	class	Meta:
		app_label = 'gw'
		ordering		= ('name', )
		verbose_name		= u'Сокращение адреса'
		verbose_name_plural	= u'Сокращения адресов'

class	AddrType(models.Model):
	'''
	Тип адреса: Домашний, Юридический, Почтовый, Доставки etc
	'''
	id		= models.PositiveSmallIntegerField(primary_key=True, verbose_name=u'Код')
	abbr		= models.CharField(max_length=6, null=False, blank=False, unique=True, verbose_name=u'Аббревиатура')
	name		= models.CharField(max_length=20, null=False, blank=False, unique=True, verbose_name=u'Наименование')

	def	asstr(self):
		return self.name

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('id', )
		verbose_name		= u'Тип адреса'
		verbose_name_plural	= u'Типы адресов'

class	Address(Object, AL_Node):
	'''
	Адрес (РФ) - рекурсивный
	'''
	name		= models.CharField(max_length=60, null=False, blank=False, verbose_name=u'Наименование')
	type		= models.ForeignKey(AddrShort, null=True, blank=True, verbose_name=u'Сокращение')
	typeplace	= models.SmallIntegerField(null=True, blank=True, verbose_name=u'Расположение сокращения')	# type пишется слева, справа, в середине
	parent		= models.ForeignKey('self', related_name='children_set', null=True, db_index=True, verbose_name=u'Предок')
	publish		= models.BooleanField(null=False, blank=False, default=False, verbose_name=u'Печатать')
	endpoint	= models.BooleanField(null=False, blank=False, default=False, verbose_name=u'Конец')
	zip		= models.PositiveIntegerField(null=True, blank=True, verbose_name=u'Индекс')
	fullname	= models.CharField(max_length=255, null=True, blank=True, verbose_name=u'Полный адрес')
	node_order_by	= ['name']

	def	__unicode__(self):
		return self.name

	def	asfullstr(self):
		retvalue = u''
		for i in self.getparents():
			retvalue = retvalue + i.name + ', '
		return retvalue + self.name

	def	mkfullname(self):
		'''
		Build full name recursively
		'''
		if self.endpoint:
			tmp = list()
			for i in self.get_ancestors():
				if i.publish:
					if i.type:
						tmp.append(i.type.name + u'. ' + i.name)
					else:
						tmp.append(i.name)
			if self.publish:
				if self.type:
					tmp.append(self.type.name + u'. ' + self.name)
				else:
					tmp.append(self.name)
			self.fullname = ', '.join(tmp)
		else:
			self.fullname = self.name

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Адрес'
		verbose_name_plural	= u'Адреса'
		ordering		= ('name',)

class	AddrKladr(models.Model):
	address		= models.OneToOneField(Address, verbose_name=u'Адрес')
	kladr		= bigint.BigForeignKey(Kladr, null=False, blank=False, db_index=True, verbose_name=u'КЛАДР')

	def	__unicode__(self):
		return self.address

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Адрес.Кладр'
		verbose_name_plural	= u'Адреса.Кладр'

class	PhoneType(models.Model):
	'''
	Тип телефона
	'''
	id		= models.PositiveSmallIntegerField(primary_key=True, verbose_name=u'Код')
	abbr		= models.CharField(max_length=5, null=False, blank=False, unique=True, verbose_name=u'Аббревиатура')
	name		= models.CharField(max_length=20, null=False, blank=False, unique=True, verbose_name=u'Наименование')

	def	asstr(self):
		return self.name

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('id', )
		verbose_name		= u'Тип телефона'
		verbose_name_plural	= u'Типы телефонов'

class	Phone(Object):
	'''
	Телефонный номер.
	'''
	no		= models.CharField(max_length=15, null=False, blank=False, unique=True, verbose_name=u'Номер')
	types		= models.ManyToManyField(PhoneType, through='Phone2Type', verbose_name=u'Типы')

	def	__unicode__(self):
		return self.no

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Телефон'
		verbose_name_plural	= u'Телефоны'
		ordering		= ('no',)

class	Phone2Type(models.Model):
	type		= models.ForeignKey(PhoneType, null=False, blank=False, verbose_name=u'Тип')
	phone		= models.ForeignKey(Phone, null=False, blank=False, verbose_name=u'Телефон')

	def	asstr(self):
		return u'%s: %s' % (self.phone, self.type)

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Телефон.Тип'
		verbose_name_plural	= u'Телефон.Типы'
		ordering		= ('phone', 'type',)
		unique_together		= (('type', 'phone',),)

class	__URL(Object):
	URL		= models.URLField(unique=True, verbose_name=u'URL')

	def	asstr(self):
		return self.URL

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('URL',)
		abstract		= True

class	WWW(Object):
	'''
	Web-ресурс.
	'''
	URL		= models.URLField(unique=True, verbose_name=u'URL')

	def	asstr(self):
		return self.URL

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'WWW'
		verbose_name_plural	= u'WWW'
		ordering		= ('URL',)

class	Email(Object):
	'''
	E-mail
	'''
	URL		= models.EmailField(unique=True, verbose_name=u'Email')

	def	asstr(self):
		return self.URL

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'E-mail'
		verbose_name_plural	= u'E-mail'
		ordering		= ('URL',)

class	IMType(models.Model):
	'''
	Тип IM
	'''
	id		= models.PositiveSmallIntegerField(primary_key=True, verbose_name=u'Код')
	name		= models.CharField(max_length=10, null=False, blank=False, unique=True, verbose_name=u'Аббревиатура')
	comments	= models.CharField(max_length=64, null=True, blank=True, verbose_name=u'Комментарии')

	def	asstr(self):
		return self.name

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('id', )
		verbose_name		= u'Тип IM'
		verbose_name_plural	= u'Типы IM'

class	IM(Object):

apps/gw/tagged/models.py
# -*- coding: utf-8 -*-
'''
TODO: all of MIME types: audio, image, text, video
(option: application, example, message, model, multipart
'''

# 1. django
from django.db import models

# 2. system

# 3. 3rd party

# 4. local
from apps.gw.bits.models import *
from django.contrib.contenttypes.models import ContentType
#from apps.gw.tagged.forms import ObjectListForm

class    TaggedObjectType(models.Model):
    '''
    Attributed Object types
    '''
    name        = models.CharField        (null=False, blank=False, max_length=64, unique=True, verbose_name=u'Наименование')
    comments    = models.CharField        (null=True, blank=True, max_length=255, verbose_name=u'Комментарий')

    def    __unicode__(self):
        return self.name

    class    Meta:
        app_label = 'gw'
        verbose_name = u'Тип теганутых объектов'
        verbose_name_plural = u'Типы теганутых объектов'

class    TaggedObjectTagType(models.Model):
    '''
    Attributes definitions for TaggedObjectType
    Type: str, bool, int, float, decimal, date, time, datetime, ... - all of Django's *Field
    FK: ct_id
    '''
    name = models.CharField(null=True, blank=True, max_length=255, verbose_name=u'Название')
    tot        = models.ForeignKey(TaggedObjectType, null=False, blank=False, verbose_name=u'Тип объекта')
    type        = models.PositiveSmallIntegerField(null=False, blank=False, verbose_name=u'Тип тега')
    multiplicity    = models.PositiveSmallIntegerField(null=False, blank=False, default=0, verbose_name=u'Множественность')    # ?|1|+|*
    options        = models.CharField(null=True, blank=True, max_length=255, verbose_name=u'Опции')    # CommaSeparated* ?

    class    Meta:
        app_label = 'gw'
        verbose_name = u'Тип тэга теганутого объекта'
        verbose_name_plural = u'Типы тэгов теганутых объектов'

    def mult_mark(self):
        marks=['?','1','+','*']
        return marks[self.multiplicity]

    def type_name(self):
        names=[u'Строка',u'Триггер',u'Число',u'Дата',u'Объект']
        name=names[self.type]
        if self.type==4:
            try:
                name+=' %s' % ContentType.objects.get(id=self.options).name
            except:
                name='error object id'
        return name

    def type_class(self):
        classes=[u'str',u'bool',u'int',u'date',u'object',u'']
        return classes[self.type]

    def __unicode__(self):
        return '%s (%s) [%s]' % (self.name, self.type_name(),self.mult_mark())

    def get_control(self):
        if self.type_class()=='bool':
            intype='checkbox'

        else:
            intype='text'
        options=''
        return '<input type="%s" id="%s" class="%s" %s>'  % (intype,self.id,self.type_class(),options)

class    TaggedObject(models.Model):
    '''
    Object with user-defined attributes.
    Not inherits Object because need handle already existant Object
    '''
    object        = models.OneToOneField(Object, related_name='master', primary_key=True, verbose_name=u'Объект', null=False, blank=True)
    tot        = models.ForeignKey(TaggedObjectType, null=False, blank=False, verbose_name=u'Тип')
    tags        = models.ManyToManyField(TaggedObjectTagType, through='TaggedObjectTag', verbose_name=u'Атрибуты', null=True, blank=True)

    class    Meta:
        app_label = 'gw'
        verbose_name = u'Теганутый объект'
        verbose_name_plural = u'Теганутые объекты'

    def __unicode__(self):
        return '%s (%s)' % (self.object, self.tot)



class    TaggedObjectTag(Object):
    '''
    Tags of TaggedObject
    '''
    object        = models.ForeignKey(TaggedObject, null=True, blank=True, verbose_name=u'Объект')
    type        = models.ForeignKey(TaggedObjectTagType, null=False, blank=False, verbose_name=u'Тип')
    value        = models.CharField(null=False, blank=True, max_length=255, verbose_name=u'Значение')

    class    Meta:
        app_label = 'gw'
        verbose_name = u'Атрибут теганутого объекта'
        verbose_name_plural = u'Атрибуты теганутых объектов'

    def __unicode__(self):
        return '%s -- %s' %(self.type,self.value)

apps/gw/file/forms.py
# -*- coding: utf-8 -*-
'''
lansite.gw.task.forms.py
'''

from django import forms

from models import *

class	FileAddForm(forms.ModelForm):
	class	Meta:
		model = File
		fields = ('file',)

class	FileEditForm(forms.ModelForm):
	class	Meta:
		model = File
		fields = ('name',)

apps/gw/forms.py
# -*- coding: utf-8 -*-
'''
lansite.gw.forms.py
'''

templates/gw/tagged/attach_file.html
{% extends "gw/tagged/base.html" %}
{% block title %} LanSite/GW/tagged {% endblock %}
{% block topbar %} TO {% endblock %}

{% block body_main %}
<h4>Прикрепление файла</h4>
{#    tagtype, existfile, [new file]<br>#}
    <form action="." method="post">
    <table>
    {{ form }}
    {{ oform }}
    </table>
            <input type="submit" value="Прикрепить"/>
    </form>
{#    <input type="button" value="Прикрепить" onclick=""/>#}
{% endblock %}

templates/gw/tagged/base.html
{% extends "base.html" %}

{% block scripts %}
        <link type="text/css" href="{% url views.index %}static/css/elen/jquery-ui-1.8.4.custom.css" rel="stylesheet">
        <link type="text/css" href="{% url views.index %}static/css/index.css" rel="stylesheet">
{#        <link type="text/css" href="{% url views.index %}static/css/jquery.ui.potato.menu.css" rel="stylesheet">    #}
        <!--Debug CSS-->
            <!--<link rel="stylesheet" href="{% url views.index %}static/css/debug.css" type="text/css">-->
    <!--JS-->
        <script type="text/javascript" src="{% url views.index %}static/js/jquery-1.4.3.min.js"></script>
{#        <script type="text/javascript" src="{% url views.index %}static/js/jquery.ui.potato.menu.js"></script>#}
        <script type="text/javascript" src="{% url views.index %}static/js/jquery-ui-1.8.5.custom.min.js"></script>
{#        <script type="text/javascript" src="{% url views.index %}static/js/jquery.dataTables.js"></script>#}
        <script type="text/javascript" src="{% url views.index %}static/js/datepicker_lang.js"></script>
{% endblock %}

templates/gw/tagged/taglist.html
{% load gw_extras %}
{% if tags %}
<h4>Список тэгов</h4>
<table>
{% for tag in tags %}
        <tr>
    <td colspan="2">{{ tag.type }} : </td>
        </tr>
        <tr>
            <td>Значение: </td>
            <td>
            <b>
                {% ifequal tag.type.type_class "bool" %}
                    {% if tag.tag.value %}
                        Да
                    {% else %}
                        Нет
                    {% endif %}
                {% else %}
                    {% if tag.tag.value %}
                                        {% ifequal tag.type.type_class 'date' %}
                {{ tag.tag.value|date:"d.m.Y" }}
                {% else %}
                        {% ifequal tag.type.type_class 'object' %}
                            {% autoescape off %}
                          {{ tag.type.options|get_obj_link:tag.tag.value }}
                            {% endautoescape %}
                        {% else %}
                {{ tag.tag.value }}
                {% endifequal %}
                                        {% endifequal %}
                    {% else %}
                        Нет значения
                    {% endif %}
                {% endifequal %}
            </b>
            </td>
            </tr>
{% endfor %}
</table>
    <input type='button' value='Редактировать' onclick="window.location='{% url gw.tagged.views.to_edit  item.id %}'" id="set_tags">
{% else %}
{% if not ttypes %}
    Тэги не установлены
    <input type='button' value='Установить' onclick="window.location='{% url gw.tagged.views.to_view  item.id %}'" id="set_tags">
{% endif %}
{% endif %}
{% if ttypes %}
    {% if context.path == 'gw' %}
    <script type="text/javascript" src="{% url views.index %}static/js/jquery-1.4.2.min.js"></script>
        {% endif %}
        Тэггировать как
    {{ ttypes }}
    <input type='button' value='Сохранить' onclick="window.location='{% url gw.tagged.views.to_add %}{{ item.id }}/'+$('#id_type').val()">
{% endif %}

templates/gw/tagged/to_search.html
{% extends "gw/tagged/base.html" %}
{% block title %} LanSite/GW/ {% endblock %}
{% block topbar %} Поиск по тэгам {% endblock %}

{% block body_main %}

    <script>

            function changeControl(){
            if($('#tagtype').val()!='---'){
                $('#newdiv').load('{% url gw.views.index %}to/getinput/'+$('#tagtype').val(),function(){
                    $('#newdiv *').attr('id','newvalue')
                $('#newvalue[class="date"]').datepicker({dateFormat: 'dd.mm.yy', changeMonth: true,}).datepicker($.datepicker.regional['ru']);
                })
            }

        }
    function addTag(){
//        alert($('#tagtype').val()+','+$('#newvalue').val())
//        $.post("","["+tagsarr+"]",function(data){
//                alert(data)
{#                location='{% url gw.tagged.views.to_view to.object.id %}'#}
//            },function(){
//            alert('Error!')
//        }
        var type=$("#tagtype").val()
        var value = $("#newvalue").val()
        var type_name = $('option[value="'+type+'"]').html()
        var tag_name = $('option[value="'+value+'"]').html()
        if(tag_name==null){

            var tag_name = $('#newvalue').val()

        }
        var delbutton='<input type="button" value="X" class="del" >'
        $('#crit').append('<li type="'+type+'" value="'+value+'">'+type_name+' - '+tag_name+delbutton+'</li>')
        $('.del').click(function(){
$(this).parent().remove()
        })
        $('#newvalue').val('')
        $('#tagtype').val('')
    }
    function doSearch(){
        var crln = $('#crit > li').length
        if(crln>0){
            crits=[]
            $("#crit > li").each(function(i,obj){
//                alert($(obj).html())
                crits.push('{"type":"'+$(obj).attr('type')+'","value":"'+$(obj).attr('value')+'"}')
            })
//            alert(crits)
            $.post(".","["+crits+"]",function(data){
//                alert(data)
{#                location='{% url gw.tagged.views.to_view to.object.id %}'#}
                $('#result').html(data)
            },function(){
            alert('Error!')
        })
        }
        else
        {
            alert('Добавьте критерий')
        }

    }
$(function(){
    $('#id_type').change(function(){
//        alert($('#id_type').val())
        $('#tagtype').val('--------')
        $('#tagtype option[type!="'+$('#id_type').val()+'"]').attr('disabled','disabled')
        $('#tagtype option[type="'+$('#id_type').val()+'"]').removeAttr('disabled')
    })
})
    </script>

{#<h3>Поиск по тэгам</h3>#}


          <h4>Новый тэг для поиска</h4>
    {{ toform }}
        {% if tags_all %}
        <form action="newtag" method="post">
<select onChange="changeControl()" id="tagtype">
    <option>--------</option>
{% for tag in tags_all %}
  <option value="{{ tag.id }}" type="{{ tag.tot.id }}" {% if tag.required %}req="true"> * {% else %}>{% endif %}{{ tag }}</option>
{% endfor %}
</select>

{#        <label for="newvalue">Значение</label>#}
        <div id="newdiv">
        </div>
            <input type="button" value="Добавить" onclick="addTag()"/>
        </form>
            {% else %}
            Нет подходящих тэгов.
            <input type="button" value="Добавить" onclick="window.location='{% url gw.tagged.views.to_tagtype_add %}'"/>
            {% endif %}

    <h4>Критерии</h4>
    <ul id='crit'>
    </ul>
    <br>
    <input type="button" value="Поиск" onclick="doSearch()"/>
    <br>
    <div id='result'>

    </div>
{% endblock %}

templates/gw/tagged/to_search_result.html
<h4>Результаты поиска</h4>
{% if result %}
    <ul id="result_list">
    {% for to in result %}
        <li><a href='{{ to.object.get_absolute_url }}'>{{ to }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    Ничего не найдено.
{% endif %}

templates/gw/tagged/to_tagtype_add.html
{% extends "gw/tagged/base.html" %}
{% block title %} LanSite/GW/ {% endblock %}
{% block topbar %} Добавить Тип{% endblock %}

{% block body_main %}

    <script>
    function objSel(){
        if($('#tag #id_type').val()==4){
//        alert($('#id_type').html())
            $('#id_options').replaceWith($('#cform select').attr('name','options').attr('id','id_options'))
            $('label[for="id_options"]').html('Тип объекта')
        }
    }

    </script>

    <div style='display: none'>
    <div id="cform">
        {{ cform }}
    </div>

    </div>

    <h3>Существующие типы</h3>
    <div style="height: 300px; overflow: scroll;">
    <ul>
    {% for type in types %}
        <li>{{ type.tot }} -- {{ type }} <input type='button' value='X' onclick="window.location='{% url gw.tagged.views.to_deltagtype type.id %}'"> </li>
    {% endfor %}
    </ul></div>
    <hr>
    <h3>Новый тип объекта</h3>
        <form action="./objtype" method="post">
    <table>
    {{ oform.as_table }}
</table>
        <input type="submit" value="Добавить"/>
    </form>
    <hr>
    <h3>Новый тип тэга</h3>
    <form action="./tagtype" method="post">
    <table id="tag">
    {{ form.as_table }}
</table>
        <input type="submit" value="Добавить"/>
    </form>
        <h4>Инструкция</h4>
    <div style="background: #ccc; padding: 6px;">
    По добовлению тэгов
    </div>

{% endblock %}