dasist/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.contrib.auth.views import login, logout

import pprint

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',		'views.index'),
	url(r'^admin/',		include(admin.site.urls)),
	url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		login),
	url(r'^logout$',	logout),
	url(r'^core/',		include('core.urls')),
	url(r'^bills/',		include('bills.urls')),
	url(r'^scan/',		include('scan.urls')),
	url(r'^about$',		'views.about'),
)

kupa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/',		include(admin.site.urls)),
    url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
    url(r'^accounts/login/$',	login),
    url(r'^logout$',		logout),
    url(r'^about$',		TemplateView.as_view(template_name='about.html'), name='about'),
    #url(r'^$',			include('medrec.urls')),
    #url(r'^$',			TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$',			'medrec.views.index'),
    url(r'^c/a/$',		'medrec.views.client_add'),
    url(r'^c/(?P<pk>\d+)/$',	'medrec.views.client_view'),
    url(r'^c/(?P<pk>\d+)/u/$',	'medrec.views.client_edit'),
    url(r'^c/(?P<pk>\d+)/d/$',	'medrec.views.client_del'),
    url(r'^c/f/(?P<abc>\d+)/$',	'medrec.views.client_set_filter_abc'),
    url(r'^c/s/(?P<sort>\d+)/$','medrec.views.client_set_sort'),
    url(r'^r/(?P<pk>\d+)/$',	'medrec.views.record_view'),
    url(r'^r/(?P<pk>\d+)/u/$',	'medrec.views.record_edit'),
    url(r'^r/(?P<pk>\d+)/d/$',	'medrec.views.record_del'),
    url(r'^r/d/$',		'medrec.views.record_set_date'),
    url(r'^r/d/(?P<date>\d+)/$','medrec.views.record_get_date'),
    url(r'^i/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_view'),
    url(r'^i/d/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_del'),
]
#urlpatterns += staticfiles_urlpatterns()

sandbox/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',				'views.index'),
	url(r'^admin/',				include(admin.site.urls)),
	url(r'^admin/jsi18n',			'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$',	'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		'django.contrib.auth.views.login'),
	url(r'^logout$',			'django.contrib.auth.views.logout'),
	url(r'^filer/',				include('filer.urls')),
	url(r'^about$',				'views.about'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reception/', include('reception.urls')),
    url(r'^clients/', include('clients.urls')),


)

apps/gw/address/models.py
# -*- coding: utf-8 -*-

'''
lansite.gw.address.models.py
'''

from django.db import models
from django.contrib.auth.models import User

apps/gw/contact/models.py
# -*- coding: utf-8 -*-

'''
lansite.gw.task.models.py

Multitask: subtasks w/o subj, desk, etc - just assignee, state
'''

from django.db import models

from gw.bits.models import *

class	Contact(Object):
	addr		= models.ManyToManyField(Address,	through='ContactAddr', verbose_name=u'Адреса')
	phone		= models.ManyToManyField(Phone,		through='ContactPhone', verbose_name=u'Телефоны')
	www		= models.ManyToManyField(WWW,		through='ContactWWW', verbose_name=u'WWW')
	email		= models.ManyToManyField(Email,		through='ContactEmail', verbose_name=u'Email')
	im		= models.ManyToManyField(IM,		through='ContactIM', verbose_name=u'IM')

#	def	__unicode__(self):
#		return self.name
	def	__unicode__(self):
		return u'Contact...'

	def	gettype(self):
		return u'Contact'

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Контакт'
		verbose_name_plural	= u'Контакты'

class	ContactAddrType(models.Model):
	'''
	Тип адреса: Юридический, Фактический
	'''
	id		= models.PositiveSmallIntegerField(primary_key=True, verbose_name=u'Код')
	name		= models.CharField(max_length=20, null=False, blank=False, unique=True, verbose_name=u'Наименование')

	def	asstr(self):
		return self.name

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('name', )
		verbose_name		= u'Тип адреса контакта'
		verbose_name_plural	= u'Типы адресов контактов'

class	ContactAddr(models.Model):
	contact		= models.ForeignKey(Contact, null=False, blank=False, verbose_name=u'Контакт')
	addr		= models.ForeignKey(Address, null=False, blank=False, verbose_name=u'Адрес')
	types		= models.ManyToManyField(ContactAddrType, through='Contact2AddrType', verbose_name=u'Типы')

	def	asstr(self):
		return u'%s: %s (%s)' % (self.contact, self.addr, self.type)

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Контакт.Адрес'
		ordering		= ('contact', 'addr',)
		unique_together		= (('contact', 'addr',),)
		verbose_name_plural	= u'Контакты.Адреса'

class	Contact2AddrType(models.Model):
	type		= models.ForeignKey(ContactAddrType, null=False, blank=False, verbose_name=u'Тип')
	caddr		= models.ForeignKey(ContactAddr, null=False, blank=False, verbose_name=u'Контакт.Адрес')

	def	asstr(self):
		return u'%s: %s' % (self.phone, self.type)

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Тип адреса контакта'
		verbose_name_plural	= u'Типы адресов контактов'
		ordering		= ('caddr', 'type',)
		unique_together		= (('type', 'caddr',),)

class	ContactPhone(models.Model):
	contact		= models.ForeignKey(Contact, null=False, blank=False, verbose_name=u'Контакт')
	phone		= models.ForeignKey(Phone, null=False, blank=False, verbose_name=u'Телефон')
	ext		= models.CharField(max_length=4, null=True, blank=True, verbose_name=u'DTMF')

	def	__unicode__(self):
		return u'%s: %s (%s)' % (self.contact, self.phone, self.ext)

	class	Meta:
		app_label = 'gw'
		ordering		= ('contact', 'phone',)
		unique_together		= (('contact', 'phone',),)
		verbose_name		= u'Контакт.Телефон'
		verbose_name_plural	= u'Контакты.Телефоны'

class	ContactWWW(models.Model):
	'''
	TODO: URL => www
	'''
	contact		= models.ForeignKey(Contact, null=False, blank=False, verbose_name=u'Контакт')
	www		= models.ForeignKey(WWW, null=False, blank=False, verbose_name=u'WWW')

	def	asstr(self):
		return u'%s: %s' % (self.contact, self.www)

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('contact', 'www',)
		unique_together		= (('contact', 'www',),)
		verbose_name		= u'Контакт.WWW'
		verbose_name_plural	= u'Контакты.WWW'

class	ContactEmail(models.Model):
	contact		= models.ForeignKey(Contact, null=False, blank=False, verbose_name=u'Контакт')
	email		= models.ForeignKey(Email, null=False, blank=False, verbose_name=u'Email')

	def	asstr(self):
		return u'%s: %s' % (self.contact, self.email)

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('contact', 'email',)
		unique_together		= (('contact', 'email',),)
		verbose_name		= u'Контакт.Email'
		verbose_name_plural	= u'Контакты.Email'

class	ContactIM(models.Model):
	contact		= models.ForeignKey(Contact, null=False, blank=False, verbose_name=u'Контакт')
	im		= models.ForeignKey(IM, null=False, blank=False, verbose_name=u'IM')

	def	asstr(self):
		return u'%s: %s: %s' % (self.contact, self.im.account, self.im.type)

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering		= ('contact', 'im',)
		unique_together		= (('contact', 'im',),)
		verbose_name		= u'Контакт.IM'
		verbose_name_plural	= u'Контакты.IM'

class	Person(Contact):
	firstname	= models.CharField(max_length=16, null=True, blank=True, verbose_name=u'Имя')
	midname		= models.CharField(max_length=24, null=True, blank=True, verbose_name=u'Отчество')
	lastname	= models.CharField(max_length=24, null=True, blank=True, verbose_name=u'Фамилия')
	birthdate	= models.DateField(null=True, blank=True, verbose_name=u'День рождения')
	sex		= models.BooleanField(null=False, blank=False, default=True, verbose_name=u'Пол')

	def	__unicode__(self):
		return u'%s %s %s' % (self.lastname, self.firstname, self.midname)

	def	gettype(self):
		return u'Person'

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Человек'
		verbose_name_plural	= u'Люди'

class	Org(Contact):
	cn		= models.CharField(max_length=64, null=False, blank=False, unique=True, verbose_name=u'Наименование')
	shortname	= models.CharField(max_length=64, null=True, blank=True, verbose_name=u'Краткое наименование')
	fullname	= models.CharField(max_length=128, null=True, blank=True, verbose_name=u'Полное наименование')
	brandname	= models.CharField(max_length=128, null=True, blank=True, verbose_name=u'Фирменное наименование')
	egruldate	= models.DateField(null=True, blank=True, verbose_name=u'Дата регистрации в ЕГРЮЛ')
	inn		= models.CharField(null=True, blank=True, max_length=12, unique=True, verbose_name=u'ИНН')
	kpp		= models.CharField(null=True, blank=True, max_length= 9, verbose_name=u'КПП')
	ogrn		= models.CharField(null=True, blank=True, max_length=15, unique=True, verbose_name=u'ОГРН')
	stuffs		= models.ManyToManyField(Person, through='OrgStuff', verbose_name=u'Штат')

	def	__unicode__(self):
		return self.cn


	def	gettype(self):
		return u'Org'

	class	Meta:
		app_label = 'gw'
		verbose_name = u'Организация'
		verbose_name_plural = u'Организации'

class	JobRole(models.Model):
	name		= models.CharField(max_length=64, blank=False, unique=True, verbose_name=u'Наименование')
	comments	= models.CharField(max_length=100, blank=True, verbose_name=u'Коментарии')

	def	asstr(self):
		retvalue = self.name
		if self.comments:
			retvalue += u' (%s)' % self.comments
		return retvalue

	def	__unicode__(self):
		return self.asstr()

	class	Meta:
		app_label = 'gw'
		ordering = ('name',)
		verbose_name = u'Должность'
		verbose_name_plural = u'Должности'

class	OrgStuff(models.Model):
	'''
	TODO: rename to Stuff
	'''
	org		= models.ForeignKey(Org, verbose_name=u'Организация')
	role		= models.ForeignKey(JobRole, verbose_name=u'Должность')
	person		= models.ForeignKey(Person, verbose_name=u'Человек')

	def	__unicode__(self):
		return u'%s, %s: %s' % (self.org, self.role, self.person)

	class	Meta:
		app_label = 'gw'
		verbose_name		= u'Организация.Должностное лицо'
		verbose_name_plural	= u'Организация.Должностные лица'
		unique_together		= [('org', 'role', 'person')]

apps/gw/models.py
# -*- coding: utf-8 -*-

'''
lansite.gw.models.py
'''

#from django.db.models import Q

from bits.models import *
from contact.models import *
from task.models import *

apps/gw/address/forms.py
# -*- coding: utf-8 -*-
'''
lansite.gw.address.forms.py
'''

from django import forms

from apps.gw.models import *
from django.db.models import Q

        
class    SelectAddressForm(forms.Form):
    address        = forms.ModelChoiceField(queryset=Address.objects.all(), label='')
    def    setdata(self, parent_id, type_id):
        if parent_id is None:
            self.fields['address'].queryset = Address.objects.filter(id__lt=247)
        else:    
            self.fields['address'].queryset = Address.objects.filter(parent__id=parent_id, type__id=type_id)
        
class    SelectAddressTypeForm(forms.Form):
    type        = forms.ModelChoiceField(queryset=AddrShort.objects.all(), label='')
    def    setdata(self, parent_id):
        if not parent_id is None:
            self.fields['type'].queryset = AddrShort.objects.filter(id__in=Address.objects.filter(parent=parent_id).values_list('type__id'))            
        
class    ContactAddressTypeForm(forms.Form):
    type        = forms.ModelChoiceField(queryset=ContactAddrType.objects.all(), label='')
    def    setdata(self, contact_id):
        self.fields['type'].queryset = ContactAddrType.objects.filter(~Q(id__in=Contact2AddrType.objects.filter(caddr__in=ContactAddr.objects.filter(contact__id=contact_id)).values_list('type__id')))
                  

apps/gw/file/forms.py
# -*- coding: utf-8 -*-
'''
lansite.gw.task.forms.py
'''

from django import forms

from models import *

class	FileAddForm(forms.ModelForm):
	class	Meta:
		model = File
		fields = ('file',)

class	FileEditForm(forms.ModelForm):
	class	Meta:
		model = File
		fields = ('name',)

apps/gw/forms.py
# -*- coding: utf-8 -*-
'''
lansite.gw.forms.py
'''

apps/gw/file/views.py
# -*- coding: utf-8 -*-
'''
lansite.gw.task.views.py
'''

# 1. django
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse, resolve
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.template import loader, Context, RequestContext

# 2. python
from datetime import datetime
import sys

# 3. my
from models import *
from forms import *

# 4. siblings
from apps.gw.tagged.forms import TypeListForm
from apps.gw.tagged.models import TaggedObjectTag

@login_required
def    file_index(request):
	return render_to_response('gw/file/index.html', context_instance=RequestContext(request))

@login_required
def    file_index_all(request):
    return render_to_response('gw/file/index_all.html', context_instance=RequestContext(request, {
        'item_list': File.objects.all(),
        'form': FileAddForm()
    }))

@login_required
def    file_index_img(request):
    '''
    '''
    return render_to_response('gw/file/index_img.html', context_instance=RequestContext(request, {
        'item_list': ImageFile.objects.all(),
        'form': FileAddForm()
    }))

@login_required
def    file_add(request):
    if request.method == 'POST':
        f = FileAddForm(request.POST, request.FILES)
        if f.is_valid():
            file = request.FILES['file']
            content_type = request.FILES['file'].content_type.split('/', 1)[0]
            #print content_type
            if (content_type == 'image'):
                ImageFile(file=file).save()
            else:
                File(file=file).save()
    return HttpResponseRedirect(reverse('gw.views.file_index'))

@login_required
def    file_detail(request, item_id):
    file = File.objects.get(pk=item_id)
    if (file.get_real_instance_class() == ImageFile):
        return file_detail_img(request, item_id)
    return render_to_response('gw/file/detail.html', context_instance=RequestContext(request, {'item': file}))

@login_required
def    file_detail_img(request, item_id):
    '''
    TODO: preview (bmp?, gif, ?ico, jpg, png) or tiff=>gif/jpg/png (1-bit, max 512)
    '''
    file = ImageFile.objects.get(pk=item_id)
    return render_to_response('gw/file/detail_img.html', context_instance=RequestContext(request, {'item': file}))

@login_required
def    file_edit(request, item_id):
    #print "edit"
    item = File.objects.get(pk=item_id)
    if request.method == 'POST':
        f = FileEditForm(request.POST, instance=item)
        if f.is_valid():
            f.save()
    else:    # GET
        f = FileEditForm(instance=item)
    return render_to_response('gw/file/edit.html', context_instance=RequestContext(request, {'item': item, 'form': f}))

@login_required
def    file_del(request, item_id):
    TaggedObjectTag.objects.filter(value=item_id).delete()
    File.objects.get(pk=item_id).delete()
    return HttpResponseRedirect(reverse('gw.views.file_index'))

@login_required
def    file_dl(request, item_id):    #def    file_dl(request, file_id, file_name):
    '''
    web.header("Content-Type", "%s/%s;" % (item.mime_media, item.mime_type))
    web.header("Content-Transfer-Encoding" , "binary");
    web.header("Content-Disposition", "attachment; filename=\"%s\";" % item.origfn);
    web.header("Content-Length", "%d" % item.size);
    return open(os.path.join(config.filepath, "%08X" % (int(item.id)))).read()
    '''
    file = File.objects.get(id=int(item_id))
    response = HttpResponse(content_type = file.mime)    # HttpResponse(mimetype='text/xml; charset=utf-8')
    response['Content-Transfer-Encoding'] = 'binary'
    # FIXME: django.http.__init__.py: ..._convert_to_ascii: value.encode('us-ascii') -> 'utf-8'
    #response['Content-Disposition'] = u'attachment; filename=\"%s\";' % file.name
    #response['Content-Disposition'] = 'attachment; filename=\"%s\";' % file.name.encode('ascii', 'xmlcharrefreplace')
    response['Content-Disposition'] = (u'attachment; filename=\"%s\";' % file.name).encode('utf-8')
    #response['Content-Length'] = u'%d;' % file.file.size
    response.write(open(file.file.path).read())
    return response

templates/gw/bits/address_base.html
<!-- Address.Base -->
{% extends "gw/bits/base.html" %}
{% block title %} Адрес {% endblock %}
{% block topbar %}
<script langauge="JavaScript" type="text/javascript">
function doMenu() {
        div=document.getElementById("div");
	exp=document.getElementById("exp");
        if (div.style.display=="none") {
                div.style.display="block";
                exp.innerHTML="&#9660;";
        }
        else {
                div.style.display="none";
                exp.innerHTML="&#9654;";
        }
}
</script>
{% endblock %}
{% block body_main %}
<!-- 1. Header -->
<p>
	<a href="{% url gw.views.address_index %}{% if next %}?next={{ next }}{% endif %}"> / </a>
	{% for i in item.get_ancestors %}
		{% if i.type %}
			<a href="{% url gw.views.address_short i.parent.id i.type.id %}{% if next %}?next={{ next }}{% endif %}"> {{ i.type.name }} </a>
		{% endif %}
		<a href="{% url gw.views.address_detail i.id %}{% if next %}?next={{ next }}{% endif %}"> {{ i.name }} </a> /
	{% endfor %}
	{% if item.type %}
		<a href="{% url gw.views.address_short item.parent.id item.type.id %}{% if next %}?next={{ next }}{% endif %}"> {{ item.type.name }} </a>
	{% endif %}
	{{ item.name }}
	{% if item.endpoint and next %}
		<a class="button" href="{{ next }}?address={{ item.id }}"> &nbsp;OK&nbsp; </a>
		<a class="button" href="{{ next }}"> &nbsp;Cancel&nbsp; </a>
	{% endif %}
</p>
<hr/>
{% block body_detail %}
{% endblock %}
{% endblock %}
{% block bottom_script %}
	setmenu("menu_gw_bits_address");
{% endblock %}

templates/gw/bits/address_edit.html
<!-- Address.Browse.Short -->
{% extends "gw/bits/address_base.html" %}
{% block body_detail %}
<form action=".{% if next %}?next={{ next }}{% endif %}" method="post">
	<table> {{ form.as_table }} </table>
	<input type="submit" value="OK"/>
	<a class="button" href="{% url gw.views.address_detail item.id %}{% if next %}?next={{ next }}{% endif %}"> Cancel </a>
</form>
{% endblock %}

templates/gw/bits/address_index.html
<!-- Address.Select.Country -->
{% extends "gw/bits/address_base.html" %}
{% block body_main %}
<form action=".{% if next %}?next={{ next }}{% endif %}" method="post">
	<table border="0"> <tr>
		<td> Выберите страну: <td>
		<td> {{ form.item }} </td>
		<td>
			<input type="submit" value="OK"/>
			{% if next %} <a class="button" href="{{ next }}"> Отказаться </a> {% endif %}
		</td>
	</tr> </table>
</form>
<script type="text/javascript"> document.getElementById('id_item').focus() </script>
{% endblock %}

templates/gw/bits/address_short.html
<!-- Address.Select.Addr -->
{% extends "gw/bits/address_base.html" %}
{% block body_detail %}
<!-- 2. Children -->
<p> <form action=".{% if next %}?next={{ next }}{% endif %}" method="post">
	Выберите {{ short }}:
	{{ form.item }}
	<input type="submit" value="OK"/>
	{% if next %} <a class="button" href="{{ next }}"> Отказаться </a> {% endif %}
</form> </p>
<script type="text/javascript"> document.getElementById('id_item').focus() </script>
<p> Еще: <a href="JavaScript:doMenu();" id=exp>&#9654;</a></p> <div id=div style="display:none">
<!-- 3. New address w/ selected short -->
<p> Новый/ая {{ short }}: </p>
<form action="{% url gw.views.address_short_add item.id short.id %}{% if next %}?next={{ next }}{% endif %}" method="post">
	<table> {{ formadd.as_table }} </table>
	<p> <input type="submit" value="OK"/> </p>
</form>
</div>
{% endblock %}

templates/gw/bits/email_index.html
z<!-- Email -->
{% extends "gw/bits/email_base.html" %}
{% block title %} Email {% endblock %}
{% block body_main %}
<table cellpadding="1">
<tr> <th> Email </th> <td class="button" colspan="2"> <a href="{% url gw.views.email_add %}" title="Добавить"> &nbsp; + &nbsp; </a> </td> </tr>
{% for item in item_list %}
	<tr>
		<td> <a href="{% url gw.views.email_detail item.id %}"> {{ item.asstr }} </a> </td>
		<td class="button"> <a title="Изменить" href="{% url gw.views.email_edit item.id %}"> &nbsp; E &nbsp; </a> </td>
		<td class="button"> <a title="Удалить" href="{% url gw.views.email_del item.id %}"> &nbsp; X &nbsp; </a> </td>
	</tr>
{% endfor %}
</table>
{% endblock %}

templates/gw/bits/im_detail.html
<!-- IM -->
{% extends "gw/bits/im_base.html" %}
{% block title %} IM {% endblock %}
{% block topbar %} <a href="{% url gw.views.im_index %}"> IM </a> {% endblock %}
{% block body_main %}
<h1> {{ item.asstr }} </h1>
<p>
	<a class="button" title="Изменить" href="{% url gw.views.im_edit item.id %}"> &nbsp; E &nbsp; </a>
	<a class="button" title="Удалить" href="{% url gw.views.im_del item.id %}"> &nbsp; X &nbsp; </a>
</p>
<!-- Contacts -->
<hr/>
<h2> Контакты: </h2>
{% for i in item.contactim_set.all %}
	<p> <a href="{% url gw.views.contact_detail i.contact.id %}"> {{ i.contact }} </a> </p>
{% endfor %}
{% endblock %}

templates/gw/bits/im_index.html
<!-- IM -->
{% extends "gw/bits/im_base.html" %}
{% block title %} IM {% endblock %}
{% block body_main %}
<table cellpadding="1">
<tr> <th> IM </th> <th> <a class="button" href="{% url gw.views.im_add %}" title="Добавить"> &nbsp; + &nbsp; </a> </th> </tr>
{% for item in item_list %}
	<tr>
	<td> <a href="{% url gw.views.im_dtl item.id %}"> {{ item.asstr }} </a> </td>
	<td>
		<a class="button" title="Изменить" href="{% url gw.views.im_edt item.id %}"> &nbsp; E &nbsp; </a>
		<a class="button" title="Удалить" href="{% url gw.views.im_del item.id %}"> &nbsp; X &nbsp; </a>
	</td>
	</tr>
{% endfor %}
</table>
{% endblock %}

templates/gw/bits/index.html
{# /GW/Bits/ #}
{% extends "gw/bits/base.html" %}
{% block title %} Атрибуты {% endblock %}

templates/gw/bits/menu.html
{# L3 menu /GW/Files/ #}
{% include "gw/menu.html" %}
<ul idref="menu_gw_bits" class="l3">
	<li id="menu_gw_bits_address"> <a href="{% url gw.views.address_index %}"> Адреса </a> </li>
	<li id="menu_gw_bits_phone"> <a href="{% url gw.views.phone_index %}"> Телефоны </a> </li>
	<li id="menu_gw_bits_www"> <a href="{% url gw.views.www_index %}"> WWW </a> </li>
	<li id="menu_gw_bits_email"> <a href="{% url gw.views.email_index %}"> Email </a> </li>
	<li id="menu_gw_bits_im"> <a href="{% url gw.views.im_index %}"> IM </a> </li>
</ul>

templates/gw/bits/phone_base.html
{% extends "sro2/main.html" %}
{% block bottom_script %}
	setmenu("menu_gw_bits_phone");
{% endblock %}

templates/gw/bits/phone_edit.html
<!-- Phone -->
{% extends "gw/bits/phone_base.html" %}
{% block contentheader %}
    Телефон
{% endblock %}

{% block content %}
<form action=".?next={{ next }}#phone" method="post">
	<table>
		{{ form.as_table() }}
	</table>
	<input type="submit" value="Записать" class='button ui-state-default eb ui-corner-left ebutton left input-button'/> </td>
	<a href="{{ next }}#phone"  class='button ui-state-default eb ui-corner-right ebutton left'> Отменить </a>
    <br>
    <br>
</form>
{% endblock %}

templates/gw/bits/phone_index.html
<!-- Phone -->
{% extends "gw/bits/phone_base.html" %}
{% block title %} Телефоны {% endblock %}
{% block body_main %}
<table cellpadding="1">
<tr> <th> № </th> <td colspan="2" class="button"> <a href="{% url gw.views.phone_add %}" title="Добавить"> &nbsp; + &nbsp; </a> </td> </tr>
{% for item in item_list %}
	<tr>
		<td> <a href="{% url gw.views.phone_detail item.id %}"> {{ item }} </a> </td>
		<td class="button"> <a title="Изменить" href="{% url gw.views.phone_edit item.id %}"> &nbsp; E &nbsp; </a> </td>
		<td class="button"> <a title="Удалить" href="{% url gw.views.phone_del item.id %}"> &nbsp; X &nbsp; </a> </td>
	</tr>
{% endfor %}
</table>
{% endblock %}