dasist/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.contrib.auth.views import login, logout

import pprint

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',		'views.index'),
	url(r'^admin/',		include(admin.site.urls)),
	url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$', 'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		login),
	url(r'^logout$',	logout),
	url(r'^core/',		include('core.urls')),
	url(r'^bills/',		include('bills.urls')),
	url(r'^scan/',		include('scan.urls')),
	url(r'^about$',		'views.about'),
)

kupa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/',		include(admin.site.urls)),
    url(r'^admin/jsi18n',	'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
    url(r'^accounts/login/$',	login),
    url(r'^logout$',		logout),
    url(r'^about$',		TemplateView.as_view(template_name='about.html'), name='about'),
    #url(r'^$',			include('medrec.urls')),
    #url(r'^$',			TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^$',			'medrec.views.index'),
    url(r'^c/a/$',		'medrec.views.client_add'),
    url(r'^c/(?P<pk>\d+)/$',	'medrec.views.client_view'),
    url(r'^c/(?P<pk>\d+)/u/$',	'medrec.views.client_edit'),
    url(r'^c/(?P<pk>\d+)/d/$',	'medrec.views.client_del'),
    url(r'^c/f/(?P<abc>\d+)/$',	'medrec.views.client_set_filter_abc'),
    url(r'^c/s/(?P<sort>\d+)/$','medrec.views.client_set_sort'),
    url(r'^r/(?P<pk>\d+)/$',	'medrec.views.record_view'),
    url(r'^r/(?P<pk>\d+)/u/$',	'medrec.views.record_edit'),
    url(r'^r/(?P<pk>\d+)/d/$',	'medrec.views.record_del'),
    url(r'^r/d/$',		'medrec.views.record_set_date'),
    url(r'^r/d/(?P<date>\d+)/$','medrec.views.record_get_date'),
    url(r'^i/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_view'),
    url(r'^i/d/(?P<pk>\d+)/(?P<img>.+)$','medrec.views.img_del'),
]
#urlpatterns += staticfiles_urlpatterns()

sandbox/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',				'views.index'),
	url(r'^admin/',				include(admin.site.urls)),
	url(r'^admin/jsi18n',			'django.views.i18n.javascript_catalog'), # hack to use admin form widgets
	#(r'^jsi18n/(?P<packages>\S+?)/$',	'django.views.i18n.javascript_catalog'),
	url(r'^accounts/login/$',		'django.contrib.auth.views.login'),
	url(r'^logout$',			'django.contrib.auth.views.logout'),
	url(r'^filer/',				include('filer.urls')),
	url(r'^about$',				'views.about'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^reception/', include('reception.urls')),
    url(r'^clients/', include('clients.urls')),


)

apps/sro2/models.py
# -*- coding: utf-8 -*-
'''
SRO2
'''

import os

from django.db import models
from django.contrib.auth.models import User
from django.utils.datastructures import SortedDict
from polymorphic import PolymorphicModel, PolymorphicManager
from treebeard.al_tree import AL_Node
from mid import get_request
###(1
from gw.models import *
###1)
#import pprint
from apps.gw.models import WordCombination
from apps.gw.contact.models import Org
#from apps.sro2.shared import log_it
from django.contrib.contenttypes.models import ContentType

from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION

def    strdatedot(date):
    if date:
        date = str(date).split('-')
        date ='%s.%s.%s' % (date[2], date[1], date[0])
    return date

def    checkuser(item, user):
    '''
    Check wether user can change this object.
    Can: if user in center branch or in same branch as item.user
    '''
    return (((user.branchuser is not None) and user.branchuser.branch.center) or ((item.user is not None) and item.user.branchuser and user.branchuser and (item.user.branchuser.branch == user.branchuser.branch)))




def    checkuser_speccase(user):
    '''
    Check is user consists in group "SpecialCase"
    '''
    speccase = False

    for group in user.groups.all():
        if (str(group) == 'SpecialCase'):
            speccase = True
            break
    return ((user.is_superuser) or speccase)


class    Branch(models.Model):
    id        = models.PositiveSmallIntegerField(primary_key=True, verbose_name=u'Код')
    name        = models.CharField(max_length=32, blank=False, unique=True, verbose_name=u'Наименование')
    center        = models.BooleanField(blank=False, default=False, verbose_name=u'Центральный')

    def get_absolute_url(self):
        return ''

    def    asstr(self):
        return self.name

    def    __unicode__(self):
        return self.asstr()

    class    Meta:
        ordering = ('name',)
        verbose_name = u'Филиал'
        verbose_name_plural = u'Филиалы'


class    BranchUser(models.Model):
    branch        = models.ForeignKey(Branch, null=False, blank=False, verbose_name=u'Филиал')
    user        = models.OneToOneField(User, null=False, blank=False, verbose_name=u'Пользователь')

    def    asstr(self):
        return u'%s.%s' % (self.branch, self.user)

    def    __unicode__(self):
        return self.asstr()

    class    Meta:
        ordering = ('branch', 'user',)
        verbose_name = u'Пользователь в филиале'
        verbose_name_plural = u'Пользователи в филиалах'
        unique_together        = (('branch', 'user'),)


class    Insurer(models.Model):
    name        = models.CharField(max_length=100, blank=False, unique=True, verbose_name=u'Наименование')
    fullname    = models.CharField(max_length=100, blank=True, unique=False, verbose_name=u'Полное наименование')

    def    asstr(self):
        return self.name

    def    __unicode__(self):
        return self.asstr()

    class    Meta:
        ordering = ('name',)
        verbose_name = u'Страховщик'
        verbose_name_plural = u'Страховщики'

class    SroType(models.Model):
    id        = models.PositiveIntegerField(primary_key=True, verbose_name=u'Код')
    name        = models.CharField(max_length=40, blank=False, unique=True, verbose_name=u'Наименование')

    def get_absolute_url(self):
        return ''

    def    asstr(self):
        return self.name

    def    __unicode__(self):
        return self.asstr()

    class    Meta:
        ordering = ('id',)
        verbose_name = u'Тип СРО'
        verbose_name_plural = u'Типы СРО'

class    Sro(ExtraObject,models.Model):
    #name          = models.CharField(max_length=40, blank=False, unique=True, verbose_name=u'Краткое наименование')
    #fullname      = models.CharField(max_length=255, blank=False, unique=True, verbose_name=u'Полное наименование')
    name          = models.ForeignKey(WordCombination, related_name='sro_name_set', verbose_name=u'Краткое наименование')
    fullname      = models.ForeignKey(WordCombination, related_name='sro_fullname_set', verbose_name=u'Полное наименование')
    displayname   = models.CharField(max_length=40, blank=False, unique=True, verbose_name=u'Отображаемое наименование')
    regno         = models.CharField(max_length=20, blank=False, unique=True, verbose_name=u'Рег. №')
    type          = models.ForeignKey(SroType, blank=False, verbose_name=u'Тип')
    own           = models.BooleanField(blank=False, default=False, verbose_name=u'Своё')
    address       = models.CharField(null=False, blank=False, max_length=255, verbose_name=u'Юридический адрес')


    def get_absolute_url(self):
        return LOGIN_REDIRECT_URL+"sro2/sro/view/%i/" % self.id        
    def    asstr(self):
        return self.name.asstr()

    def    __unicode__(self):
        return self.asstr()

    class    Meta:
    #    ordering = ('name',)
        verbose_name = u'СРО'
        verbose_name_plural = u'СРО'

class    SroOwn(ExtraObject,models.Model):
    sro              = models.OneToOneField(Sro, verbose_name=u'СРО')
    effector         = models.ForeignKey(WordCombination, related_name='sroown_effector_set', verbose_name=u'Наименование исполнительного органа СРО')
    manage           = models.ForeignKey(WordCombination, related_name='sroown_manage_set', verbose_name=u'Наименование постоянно действующего коллегиального органа управления СРО')
    managechief      = models.ForeignKey(WordCombination, related_name='sroown_managechief_set', verbose_name=u'Наименование руководителя постоянно действующего коллегиального органа управления СРО')
    effectorfull     = models.ForeignKey(WordCombination, related_name='sroown_neffectorfull_set', verbose_name=u'ФИО исполнительного органа СРО (полное)')
    managefull       = models.ForeignKey(WordCombination, related_name='sroown_managefull_set', verbose_name=u'ФИО руководителя постоянно действующего коллегиального органа управления СРО (полное)')
    managedeputyfull = models.ForeignKey(WordCombination, related_name='sroown_managedeputyfull_set', verbose_name=u'ФИО заместителя руководителя постоянно действующего коллегиального органа управления СРО (полное)')
    signdeputy       = models.BooleanField(blank=False, default=False, verbose_name=u'Заместитель подписывает документы')

    tplprefix        = models.CharField(max_length=10, null=False, blank=False, verbose_name=u'Префикс шаблонов')
    ftp              = models.CharField(max_length=50, null=True, blank=True, verbose_name=u'FTP')	# ftp host to upload
    path             = models.CharField(max_length=100, null=True, blank=True, verbose_name=u'Path')	# ftp path to upload
    sshhost	         = models.CharField(max_length=50, null=True, blank=True, verbose_name=u'SSH host')
# to delete {   
    bosstitle        = models.CharField(max_length=50, null=False, blank=False, verbose_name=u'Должность начальника')
    boss             = models.CharField(max_length=20, null=False, blank=False, verbose_name=u'ФИО заместителя руководителя постоянно действующего коллегиального органа управления СРО (краткое)')
# } to delete   


    def get_absolute_url(self):
        return LOGIN_REDIRECT_URL+"sro2/sro/view/%i/" % self.id

    def    asstr(self):
        return self.sro.name.asstr()

    def    __unicode__(self):
        return self.asstr()

#    def save(self, force_insert = False, force_update = False):
#        ExtraObject.save(self,force_insert, force_update)

    class    Meta:
        ordering = ('sro',)
        verbose_name = u'СРО.Своё'
        verbose_name_plural = u'СРО.Свои'


class    StageVer(models.Model):
    id        = models.PositiveSmallIntegerField(primary_key=True, verbose_name=u'Код')
    name        = models.CharField(max_length=10, blank=False, unique=True, verbose_name=u'Наименование')

    def    __unicode__(self):
        return self.name

    class    Meta:
        ordering = ('id',)
        verbose_name = u'Версия видов работ'
        verbose_name_plural = u'Версии видов работ'


class    Stage(AL_Node):
    id        = models.PositiveIntegerField(primary_key=True, verbose_name=u'Код')
    ver        = models.ForeignKey(StageVer, null=False, blank=False, verbose_name=u'Версия')
    srotype        = models.ForeignKey(SroType, blank=False, verbose_name=u'Тип СРО')
    no        = models.PositiveSmallIntegerField(null=False, blank=False, verbose_name=u'№ п/п')
    code        = models.CharField(max_length=10, blank=False, verbose_name=u'Код')
    parent        = models.ForeignKey('self', related_name='children_set', null=True, blank=True, db_index=True, verbose_name=u'Предок')
    name        = models.CharField(max_length=255, blank=False, verbose_name=u'Наименование')
    isgroup        = models.BooleanField(blank=False, default=False, verbose_name=u'Группа')
    dangeronly    = models.BooleanField(blank=False, default=False, verbose_name=u'Только опасный')
    node_order_by    = ['id']

    def    asstr(self):
        return u'%s %s' % (self.code, self.name)

    def    __unicode__(self):
        return self.asstr()

    def get_absolute_url(self):
        return LOGIN_REDIRECT_URL+"admin/sro2/stage/%i/" % self.id
    
    class    Meta:
        ordering = ('srotype', 'no',)
        verbose_name = u'Вид работ'
        verbose_name_plural = u'Виды работ'

class    EventType(models.Model):
    name        = models.CharField(max_length=40, blank=False, unique=True, verbose_name=u'Наименование')
    comments    = models.CharField(max_length=100, blank=True, verbose_name=u'Коментарии')

    def    asstr(self):
        return self.name

    def    __unicode__(self):
        return self.asstr()

    class    Meta:
        verbose_name = u'Тип события'
        verbose_name_plural = u'Типы событий'

class    Agent(models.Model):
    name        = models.CharField(max_length=50, null=False, blank=False, verbose_name=u'Наименование')

    def    asstr(self):
        return self.name

    def    __unicode__(self):

apps/sro2/alienpermit/views.py
# -*- coding: utf-8 -*-
'''
Alien permit views
'''
from sro2.shared import *

@login_required
def    alienpermit_add(request, orgsro_id):
    orgsro = OrgSro.objects.get(pk=orgsro_id)
    if request.method == 'POST':
        form = PermitAddForm(request.POST)
        if form.is_valid():
            permit = None
            try:
                permit = AllienPermit(
                    no=form.cleaned_data['no'],
                    date=form.cleaned_data['date'],
                    protocol=form.cleaned_data['protocol'],
                    statement=form.cleaned_data['statement'],
                    orgsro=orgsro,
                    ver=form.cleaned_data['ver']
                )
                permit.save()
            except:
                transaction.rollback()
            else:
                transaction.commit()
            if permit is not None:
                __log_it(request, permit, ADDITION)
                transaction.commit()
            return redirect(orgsro_stagelist_edit,orgsro_id=orgsro.id)
    else:
        form = PermitAddForm()
    form.setdata(orgsro)
    return HttpResponse('ZOMFG!! Aliens attack!!!')
    #return render_to_response('sro2/alienpermit/alienpermit_add.html', RequestContext(request, {'orgsro': orgsro, 'form': form, 'type': 'Свидетельство'}))

apps/sro2/sro/views.py
# -*- coding: utf-8 -*-
'''
Sro views
-------------
'''
from sro2.shared import *

@render_to('sro2/sro/sro_list.html')
def sro_list(request):
    sros=SroOwn.objects.all()
    return {'sros':sros}

@render_to('sro2/sro/sro_new.html')
def sro_new(request):
    if not request.method == 'POST':
        soform=SroOwnForm()
        sform=SroForm()
        return {'soform':soform,'sform':sform}
    else:
        return sro_save(request)

@render_to('sro2/sro/sro_edit.html')
def sro_edit(request,sro_id):
    if not request.method == 'POST':
        sro=SroOwn.objects.get(pk=sro_id)
        soform=SroOwnForm(instance=sro)
        sform=SroForm(instance=sro.sro)
        return {'sro':sro,'soform':soform,'sform':sform}
    else:
        return sro_save(request,sro_id)

def sro_save(request,sro_id=''):
    if not sro_id:
        soform=SroOwnForm(request.POST)
        sform=SroForm(request.POST)
    else:
        so=SroOwn.objects.get(pk=sro_id)
        soform=SroOwnForm(request.POST,instance=so)
        sform=SroForm(request.POST,instance=so.sro)
    if sform.is_valid() and soform.is_valid():
        if not sro_id:
            item=sform.save()
            so=soform.save(commit=False)
            so.sro=item
            so.save()
        else:
            soform.save()
            sform.save()
        return redirect(sro_view,sro_id=so.id)
    else:
        if not sro_id:
            return jrender_to_response('sro2/sro/sro_new.html', {'sform':sform,'soform':soform},request)
        else:
            return jrender_to_response('sro2/sro/sro_edit.html', {'sform':sform,'soform':soform,'sro':Sro.objects.get(pk=sro_id)},request)

def sro_del(request,sro_id):
    so=SroOwn.objects.get(pk=sro_id)
    so.sro.delete()
    so.delete()
    return redirect(sro_list)

@render_to('sro2/sro/sro_view.html')
def sro_view(request,sro_id):
    sro=SroOwn.objects.get(pk=sro_id)
    return {'sro':sro}

templates/sro2/orglist/orglist_find.html
{% extends "sro2/main.html" %}

{% block contentheader %}
    Поиск
{% endblock %}

{% block content %}
    <body onLoad="onLoad();">

    <script language="JavaScript" type="text/javascript">
        function onLoad() {
            select = document.getElementById("select_stage_id");
            for (i = 0; i < select.options.length; i++) {
                if (select.options[i].text.length >= 173) select.options[i].text = select.options[i].text.substr(0, 173) + "...";
            }

            select = document.getElementById("select_stage_old_id");
            for (i = 0; i < select.options.length; i++) {
                if (select.options[i].text.length >= 173) select.options[i].text = select.options[i].text.substr(0, 173) + "...";
            }

        }
        function selectsClearNew() {
            document.getElementById("select_stage_old_id").options[0].selected = true;
        }

        function selectsClearOld() {
            document.getElementById("select_stage_id").options[0].selected = true;
        }

    </script>
    <form action="{% url sro2.views.orglist_find sro.id%}" method="POST">

        Виды работ по новой классификации:
        <select name="select_stage" id="select_stage_id" style="width: 100%;" onChange="selectsClearNew()">
            <option value=""></option>
            {% for stage in stage_list %}
                <option value="{{ stage.id }}"
                        id="select_option_{{ stage.id }}"> {{ stage.code }}. {{ stage.name }} </option>
            {% endfor %}
        </select>

        Виды работ по старой классификации:
        <select name="select_stage_old" id="select_stage_old_id" style="width: 100%;" onChange="selectsClearOld()">
            <option value=""></option>
            {% for stage in stage_list_old %}
                <option value="{{ stage.id }}"
                        id="select_option_{{ stage.id }}"> {{ stage.code }}. {{ stage.name }}</option>
            {% endfor %}
        </select>

        <input type="submit" value="Показать организации"
               title="Показать членов СРО, имеющих действующее свидетельство по выбранному типу работ"/>

    </form>
    <br>
    {% if stage %}
        {{ stage.code }}. {{ stage.name }}:
        {% if orgsro_list %}
            <ol>
            {% for orgsro in orgsro_list %}
                <li><a href="{% url sro2.views.orgsro_view orgsro.id %}"
                       title="{{ orgsro.org.fullname }}">{{ orgsro.org.name }}</li>
            {% endfor %}
        {% else %}
            <p>организаций нет</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/sro2/orglist/orglist_find_filter.html
{% load sro2_extras %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>LanSite.СРО2.{{ sro.name }}.Поиск.{{ stage.name }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>

<center><h1>
    <a href="{% url views.index %}"> LanSite </a> &gt;
    <a href="{% url sro2.views.index %}"> СРО2 </a> &gt;
    <a href="{% url sro2.views.index_sro sro.id %}"> {{ sro.name }} </a> &gt;
    <a href="{% url sro2.views.sro_find sro.id %}"> Поиск </a> &gt;
    {{ stage.no }}. {{ stage.name }}
</h1></center>
<hr/>
{% if orgsro_list %}
    <ol>
    {% for orgsro in orgsro_list %}
        <li><a href="{% url sro2.views.orgsro_view orgsro.id %}" title="{{ orgsro.org.fullname }}">{{ orgsro.org.name }}
        </li>
    {% endfor %}
{% endif %}
</body>
</html>

templates/sro2/orglist/orglist_mailto.html
{% extends "sro2/main.html" %}

{% block contentheader %}
    Отправить Электронную почту
{% endblock %}

{% block content %}
    <style>
        #mailto {
            width: 100%;
            height: 400px;
        }

        #wrap {
            margin: 0 10px 0 10px;
        }
    </style>
    <p><a href="mailto:{{ mailto }}"> Ссылка для копирования </a></p>
    <div id='wrap'>
        <textarea id='mailto'>{{ mailto }}</textarea>
    </div>
{% endblock %}

templates/sro2/orglist/orglist_member.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title> {{ orgsro.org.name }} </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">
        body {
            font-family: Serif;
            font-size: small;
        }

        H1 {
            font-size: large;
            text-align: center;
        }

        H2 {
            font-size: medium;
        }
    </style>
</head>
<body>

<h1> {{ orgsro.org.okopf.shortname }} {{ orgsro.org.name }} </h1>

<!-- main -->
<hr/>
<h2> Основные данные: </h2>
<table border="0">
    <tr>
        <td> Краткое наименование:</td>
        <td> {{ orgsro.org.okopf.shortname }} {{ orgsro.org.shortname }} </td>
    </tr>
    <tr>
        <td> Полное наименование:</td>
        <td> {{ orgsro.org.okopf.name }} {{ orgsro.org.fullname }} </td>
    </tr>
    <tr>
        <td> ИНН:</td>
        <td> {{ orgsro.org.inn }} </td>
    </tr>
    <tr>
        <td> КПП:</td>
        <td> {{ orgsro.org.kpp }} </td>
    </tr>
    <tr>
        <td> {{ orgsro.org.ogrn_label }}:</td>
        <td> {{ orgsro.org.ogrn }} </td>
    </tr>
    <tr>
        <td> ОКАТО:</td>
        <td> {{ orgsro.org.okato }} </td>
    </tr>
    <tr>
        <td> Адрес юридический:</td>
        <td> {{ orgsro.org.laddress }} </td>
    </tr>
    <tr>
        <td> Адрес фактический:</td>
        <td> {{ orgsro.org.raddress }} </td>
    </tr>
    <tr>
        <td> Реестровый №:</td>
        <td> {{ orgsro.regno }} </td>
    </tr>
    <tr>
        <td> Дата членства в НП:</td>
        <td> {{ orgsro.regdate|date }} </td>
    </tr>
    {% if orgsro.status == 3 %}
	<tr>
	    <td> Дата исключения:</td>
	    <td> {{ orgsro.excludedate|date("d.m.Y") }} </td>
	</tr>
	<tr>
	    <td> Причина исключения:</td>
	    <td>{% for r in orgsro.reason.all() %} {{ r.title }};<br> {% endfor %} </td>
	</tr>
	<tr>
	    <td> Протокол-основание исключения:</td>
	    <td> {{ orgsro.exprotocol }} </td>
	</tr>
    {% endif %}
</table>

<!-- okved -->
<hr/>
<h2> ОКВЭД: </h2>
<ul> {% for i in orgsro.org.okveds.all() %}
    <li> {{ i.asstr() }} </li> {% endfor %} </ul>

<!-- phone -->
<hr/>
<h2> Телефоны: </h2>
<ul> {% for i in orgsro.org.contactphone_set.all() %}
    <li> {{ i.asstr() }} </li> {% endfor %} </ul>

<!-- email -->
<hr/>
<h2> Email: </h2>
<ul> {% for i in orgsro.org.contactemail_set.all() %}
    <li><a href="mailto:{{ i.asstr() }}"> {{ i.asstr() }} </a></li> {% endfor %} </ul>

<!-- www -->
<hr/>
<h2> WWW: </h2>
<ul> {% for i in orgsro.org.contactwww_set.all() %}
    <li><a href="{{ i.asstr() }}"> {{ i.asstr() }} </a></li> {% endfor %} </ul>

<!-- stuff -->
<hr/>
<h2> Персонал: </h2>
<ul>
{% for i in person_list %}
	<li> {{ i.person.asstr() }} - {{ i.role.asstr() }} </li>
{% endfor %}
</ul>

<!-- permit -->
<hr/>
<h2> Действующее свидетельство о допуске: </h2>
{% if orgsro.currperm %}
	<p><a href="../permit/{{ orgsro.currperm.id }}.html"> № {{ orgsro.currperm.no }} от {{ orgsro.currperm.date|date }},
	    протокол № {{ orgsro.currperm.protocol.no }} от {{ orgsro.currperm.protocol.date|date }} </a></p>
{% else %}
	Нет
{% endif %}
<h3> История изменения: </h3>
<ul>
    {% for item in history %}
        <li>
            {% if item.status == 1 %}
                Действие Свидетельства приостановлено с {{ item.date|date }} по {{ item.get_datetill()|date }} в отношении
                всех видов работ в соотвествии со статьей 55.5 ГрКРФ на основании
                решения {{ item.protocol.asstr_short() }}, протокол № {{ item.protocol.no }}
                от {{ item.protocol.date|date }}, на срок {{ item.get_daystill() }} календарный дней.
            {% endif %}
            {% if item.status == 2 %}
                Действие Свидетельства возобновлено с {{ item.date|date }} в отношении всех видов работ на основании
                решения {{ item.protocol.asstr_short() }}, протокол № {{ item.protocol.no }}
                от {{ item.protocol.date|date }}.
            {% endif %}
        </li>
    {% endfor %}
</ul>
<h2> Ранее выданные свидетельство о допуске: </h2>
<ul>
    {% for item in permits %}
	{% if item !=  orgsro.currperm %}
        <li> <a href="../permit/{{ item.id }}.html"> № {{ item.no }} от {{ item.date|date }}, протокол
            № {{ item.protocol.no }} от {{ item.protocol.date|date }} </a> </li>
	{% endif %}
    {% endfor %}
</ul>

</body>
</html>

templates/sro2/orglist/orglist_org_add.html
{% extends "sro2/main.html" %}

{% block contentheader %}
    Добавление организации в {{ sro.name }}
{% endblock %}

{% block content %}
    <style type="text/css">
        #id_fullname {
            height: 60px;
        }
    </style>
    <script>
        $(
         function() {
             $('#id_egruldate').datepicker({dateFormat: 'dd.mm.yy',changeMonth: true,})
         }).datepicker($.datepicker.regional['ru']);
    </script>
    *Цветом выделены обязательные поля.
    <form action=".#org" method="POST">
        <table width="100%" border="1" id='orgadd'>
            {{ form.as_table() }}
        </table>
        <input type="submit" value="Записать и закрыть"/>
        <input type="button" value="Отказаться"
               onClick="window.location.href='{{ url_for('sro2.orglist.views.orglist_list', sro.id) }}'"/>
    </form>
{% endblock %}